// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJ8tf6EWVfUN3B7Pr6T9jH-1QrC6OpjY',
    appId: '1:348850748561:web:dabe57125b0f1380e19330',
    messagingSenderId: '348850748561',
    projectId: 'random-chat-5ebcf',
    authDomain: 'random-chat-5ebcf.firebaseapp.com',
    storageBucket: 'random-chat-5ebcf.firebasestorage.app',
    measurementId: 'G-5FGWN8L692',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZLW4R2nWxVCcdOTtf1S23uMHYMd_e-4',
    appId: '1:348850748561:android:f3e59b8c294bcfcbe19330',
    messagingSenderId: '348850748561',
    projectId: 'random-chat-5ebcf',
    storageBucket: 'random-chat-5ebcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeZCNgW1k4rZMXM6Elo4m1gtdqaAFky0',
    appId: '1:348850748561:ios:7e5e70b06801d204e19330',
    messagingSenderId: '348850748561',
    projectId: 'random-chat-5ebcf',
    storageBucket: 'random-chat-5ebcf.firebasestorage.app',
    iosBundleId: 'com.example.randomChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaeZCNgW1k4rZMXM6Elo4m1gtdqaAFky0',
    appId: '1:348850748561:ios:7e5e70b06801d204e19330',
    messagingSenderId: '348850748561',
    projectId: 'random-chat-5ebcf',
    storageBucket: 'random-chat-5ebcf.firebasestorage.app',
    iosBundleId: 'com.example.randomChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcJ8tf6EWVfUN3B7Pr6T9jH-1QrC6OpjY',
    appId: '1:348850748561:web:12b4e72d0ec24743e19330',
    messagingSenderId: '348850748561',
    projectId: 'random-chat-5ebcf',
    authDomain: 'random-chat-5ebcf.firebaseapp.com',
    storageBucket: 'random-chat-5ebcf.firebasestorage.app',
    measurementId: 'G-15Q82KXESH',
  );
}
